import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className="main-container">
          <div className="title__wrapper">
            <Image
              src="/images/wolt-logo.svg"
              alt="wolt logo"
              width={200}
              height={75}
            />
            <div className="text--h1">Delivery Fee Calculator</div>
            <div className="text--sh1">
              <div>
                Calculate with confidence! No surprises in delivery prices
              </div>
              <div>your convenience, our commitment. 📦💰</div>
            </div>
          </div>
          Calculator card
        </div>
      </main>
    </>
  );
}
